move_to_end function was improved
RaymondBalise/tidyREDCap pull request #29
Opened 2022-10-07 16:29 UTC by AnnaCalderon

move_to_end function was improved to detect if "labelled" is before "hms" even if labelled is not the first element. Addressing the warning in line 100.

2022-10-08 17:27 UTC, RaymondBalise requested changes
Plase lint and style the code

2022-10-08 17:28 UTC, RaymondBalise commented
Please add our orcID to the description file

2022-10-11 23:40 UTC, AnnaCalderon commented
>

2022-10-11 23:46 UTC, AnnaCalderon commented
lint and style the code donde

2022-10-11 23:47 UTC, AnnaCalderon commented
orcID added in a separate branch and merged.

2022-10-19 15:43 UTC, RaymondBalise requested changes

2022-10-19 15:43 UTC, RaymondBalise commented on R/make_instrument_auto.R
> +      if(which(x =="hms") > which(x == "labelled")){
Please lint the code.  Notice the missing space between =="hms"

2022-10-21 15:07 UTC, merged