Fix parenthesis in labels bug in make_instruments()
RaymondBalise/tidyREDCap pull request #41
Opened 2022-11-22 00:39 UTC by RaymondBalise

Closes #40.  Please test on complicated datasets before approving.

2022-11-29 14:26 UTC, wdefreitas requested changes
Is the Double Ampersand needed in line 117? 

Also, I think fix works when there is one set of parentheses, but if you have multiple (i.e. (blah(blah))), it does not keep the formatting of the variable label.

2022-11-29 17:53 UTC, RaymondBalise commented
The && or & give the same answer because the arguments are not vectorized.

2022-11-30 12:12 UTC, RaymondBalise commented
I don't have an easy solution for the double nested parentheses.  If it comes up again I will try to fix it.  Anything else?

2022-11-30 15:10 UTC, AnnaCalderon approved these changes

2022-12-02 17:51 UTC, merged